Disable the xcodebuild step.

diff --git a/examples/ios_sim/do_test b/examples/ios_sim/do_test
--- a/examples/ios_sim/do_test
+++ b/examples/ios_sim/do_test
@@ -6,27 +6,27 @@ set -o errexit -o nounset -o pipefail
 # version to use. Ideally, we would pass the path to the binary.  For now, we
 # will count on the fact that it expects to find `bazel` in the PATH.
 if [[ -n "${BIT_BAZEL_BINARY:-}" ]]; then
-  bazel="${BIT_BAZEL_BINARY}"
-  tmp_dir="$(mktemp -d)"
-  ln -s "${BIT_BAZEL_BINARY}" "${tmp_dir}/bazel"
-  export PATH="${tmp_dir}:${PATH}"
+	bazel="${BIT_BAZEL_BINARY}"
+	tmp_dir="$(mktemp -d)"
+	ln -s "${BIT_BAZEL_BINARY}" "${tmp_dir}/bazel"
+	export PATH="${tmp_dir}:${PATH}"
 else
-  bazel="bazel"
+	bazel="bazel"
 fi
 
 print_and_run() {
-  local cmd="${1}"
-  shift 1
-  printf >&2 "======================\n%s: %s %s\n======================\n" \
-    "$(basename "${BASH_SOURCE[0]}")" "$(basename "${cmd}")" "$*"
-  "${cmd}" "$@"
+	local cmd="${1}"
+	shift 1
+	printf >&2 "======================\n%s: %s %s\n======================\n" \
+		"$(basename "${BASH_SOURCE[0]}")" "$(basename "${cmd}")" "$*"
+	"${cmd}" "$@"
 }
 
 # Remove the temp directory if we created it.
 cleanup() {
-  if [[ -n "${tmp_dir:-}" ]]; then
-    rm -rf "${tmp_dir}"
-  fi
+	if [[ -n "${tmp_dir:-}" ]]; then
+		rm -rf "${tmp_dir}"
+	fi
 }
 trap cleanup EXIT
 
@@ -42,12 +42,9 @@ print_and_run "${bazel}" run //:xcodeproj
 # https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2355
 print_and_run "${bazel}" clean --expunge
 
-# DEBUG BEGIN
-echo >&2 "*** CHUCK $(basename "${BASH_SOURCE[0]}") ---"
-# DEBUG END
-
-# Build the FooTests scheme in the Xcode project
-print_and_run xcodebuild -project App.xcodeproj -scheme FooTests
+# GH1678: Enable this once the underlying build failure is addressed.
+# # Build the FooTests scheme in the Xcode project
+# print_and_run xcodebuild -project App.xcodeproj -scheme FooTests
 
 # Ensure that it builds and tests pass
 print_and_run "${bazel}" test //...
