Save work. rules_bazel_integration_test is not working at all now.

diff --git a/examples/firebase_example/do_test b/examples/firebase_example/do_test
--- a/examples/firebase_example/do_test
+++ b/examples/firebase_example/do_test
@@ -2,8 +2,6 @@
 
 set -o errexit -o nounset -o pipefail
 
-script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
-
 print_and_run() {
   local cmd="${1}"
   shift 1
@@ -15,6 +13,11 @@ print_and_run() {
 # Use the Bazel binary specified by the integration test. Otherise, fall back 
 # to bazel.
 bazel="${BIT_BAZEL_BINARY:-bazel}"
+
+# DEBUG BEGIN
+echo >&2 "*** CHUCK $(basename "${BASH_SOURCE[0]}") MADE IT" 
+exit 1
+# DEBUG END
 
 # Generate Swift external deps and update build files
 print_and_run "${bazel}" run //:tidy
@@ -29,30 +32,30 @@ print_and_run "${bazel}" test //...
 # https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2703
 
 
-# Generate a bazel script for rules_xcodeproj to use. This script ensures that
-# the xcodeproj runner uses the Bazel that is under test. We configure the
-# xcodeproj macro to find this generated bazel script.
-bazel_for_xcodeproj="${script_dir}/bazel_for_xcodeproj"
-backup="${bazel_for_xcodeproj}.bak"
-cleanup() {
-  if [[ -e "${backup}" ]]; then
-    mv -f "${backup}" "${bazel_for_xcodeproj}"
-  fi
-}
-trap cleanup EXIT
-mv -f "${bazel_for_xcodeproj}" "${backup}"
-cat >"${bazel_for_xcodeproj}" <<-EOF
-#!/usr/bin/env bash
-
-set -o errexit -o nounset -o pipefail
-
-# Use the Bazel binary that we specify.
-bazel="${bazel}"
-
-# Execute the Bazel command
-"\${bazel}" "\${@}"
-EOF
-chmod +x "${bazel_for_xcodeproj}"
+# # Generate a bazel script for rules_xcodeproj to use. This script ensures that
+# # the xcodeproj runner uses the Bazel that is under test. We configure the
+# # xcodeproj macro to find this generated bazel script.
+# bazel_for_xcodeproj="${script_dir}/bazel_for_xcodeproj"
+# backup="${bazel_for_xcodeproj}.bak"
+# cleanup() {
+#   if [[ -e "${backup}" ]]; then
+#     mv -f "${backup}" "${bazel_for_xcodeproj}"
+#   fi
+# }
+# trap cleanup EXIT
+# mv -f "${bazel_for_xcodeproj}" "${backup}"
+# cat >"${bazel_for_xcodeproj}" <<-EOF
+# #!/usr/bin/env bash
+# 
+# set -o errexit -o nounset -o pipefail
+# 
+# # Use the Bazel binary that we specify.
+# bazel="${bazel}"
+# 
+# # Execute the Bazel command
+# "\${bazel}" "\${@}"
+# EOF
+# chmod +x "${bazel_for_xcodeproj}"
 
 # Generate the Xcode project
 print_and_run "${bazel}" run //analytics/AnalyticsExample:xcodeproj
